projectrecipe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),

    path('', include('recipelist.urls')),
    # other URL patterns
]

recipelist/urls.py
from django.urls import path, include
from . import views
from graphene_django.views import GraphQLView
from django.views.generic import TemplateView



app_name = 'recipelist'
urlpatterns=[
    path("", views.index, name='index'),
    path("index.html/", views.index, name='index'),

    path("get_ingredients/", views.get_ingredients, name='get_ingredients'),
    path('search/', views.search, name='search'),
    path('adjusted_search/', views.adjusted_search, name='adjusted_search'),
    path('grocery_list/', views.grocery_list, name='grocery_list'),
    #path("graphql", GraphQLView.as_view(graphiql=True), schema=schema),
    path("graphql/", (GraphQLView.as_view(graphiql=True))),
    #path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('login_heb/', views.login_heb, name='login_heb'),

]

recipelist/models.py
from django.db import models

class Groceries(models.Model):
    item = models.CharField(max_length=100)
    list = models.TextField()

    def __str__(self):
        return self.item

recipelist/views.py
from django.shortcuts import render
from bs4 import BeautifulSoup
import requests
from django.http import HttpResponse
from fractions import Fraction
from django.shortcuts import render, redirect
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
import os
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from urllib.parse import quote



ingredients=[]

def index(request):
    return render(request, 'recipelist/index.html')

def get_ingredients(request):
    if request.method == 'POST':
        url = request.POST['url']
        page = requests.get(url)
        soup = BeautifulSoup(page.content, 'html.parser')
        stars_html = soup.find(id='mntl-recipe-review-bar__rating_2-0')
        ingredients_html = soup.find(class_='mntl-structured-ingredients__list')
        directions_html= soup.find(class_='comp mntl-sc-block-group--OL mntl-sc-block mntl-sc-block-startgroup')
        ingredients = []
        directions = []
        stars = ''
        if stars_html:
            stars = stars_html.text
        if ingredients_html:
            for li in ingredients_html.find_all('li'):
                ingredients.append(li.text.strip())
        if directions_html:
            for li in directions_html.find_all('li'):
                directions.append(li.text.replace('.', '--').strip())

        context = {
            'url': url,
            'stars': stars,
            'ingredients': ingredients,
            'directions': directions,
        }

        return render(request, 'recipelist/ingredients.html', context)

    else:
        return render(request, 'recipelist/index.html')






def search(request):
    query = request.GET.get('q', '')
    url = f"https://www.google.com/search?q={query} site:allrecipes.com"
    page = requests.get(url)
    soup = BeautifulSoup(page.content, 'html.parser')
    search_results = soup.find_all('a')

    recipe_url = None
    for link in search_results:
        link_url = link.get('href')
        if link_url.startswith('/url?q=https://www.allrecipes.com/recipe/') and 'search' not in link_url:
            recipe_url = link_url.split('&')[0][7:]
            break

    if not recipe_url:
        return render(request, 'search.html', {'error_message': 'No recipe found.'})

    recipe_page = requests.get(recipe_url)
    recipe_soup = BeautifulSoup(recipe_page.content, 'html.parser')

    recipe_title = soup.find("title").text
    title, source = recipe_title.split(":")


    recipe_details = recipe_soup.find('div', {'class': 'comp recipe-details mntl-recipe-details'})
    details_items = recipe_details.find_all('div', {'class': 'mntl-recipe-details__item'})

    for item in details_items:
        label = item.find('div', {'class': 'mntl-recipe-details__label'}).text.strip()
        if label == 'Servings:':
            servings = item.find('div', {'class': 'mntl-recipe-details__value'}).text.strip()
            break
    else:
        servings = None


    stars = recipe_soup.find(id='mntl-recipe-review-bar__rating_2-0')
    if stars:
        stars_text = f'{stars.text} -- Ingredients:  '
    else:
        stars_text = 'Could not find stars information.'

    ingredients = []
    ingredients_html = recipe_soup.find(class_='mntl-structured-ingredients__list')
    for li in ingredients_html.find_all('li'):
        ingredients.append(li.text.strip())

    directions = []
    directions_html = recipe_soup.find(class_='comp mntl-sc-block-group--OL mntl-sc-block mntl-sc-block-startgroup')
    for li in directions_html.find_all('li'):
        directions.append(li.text.replace('.', '--').strip())

    context = {
        'recipe_url': recipe_url,
        'stars_text': stars_text,
        'servings': servings,
        'ingredients': ingredients,
        'directions': directions,
        'recipe_title': recipe_title,
        'title':title,
        'source':source,
    }
    return render(request, 'recipelist/search.html', context)



def adjusted_search(request):
    servings = request.GET.get('servings', '')
    recipe_url = request.GET.get('recipe_url', '')
    if not servings or not recipe_url:
        return redirect('search')

    try:
        servings = int(servings)
        if servings < 1 or servings > 10:
            raise ValueError
    except ValueError:
        return redirect('search')

    recipe_page = requests.get(recipe_url)
    recipe_soup = BeautifulSoup(recipe_page.content, 'html.parser')

    recipe_title = recipe_soup.find("title").text
    if ':' in recipe_title:
        title, source = recipe_title.split(":")
    else:
        title = recipe_title
        source = "Unknown"

    recipe_details = recipe_soup.find('div', {'class': 'comp recipe-details mntl-recipe-details'})
    details_items = recipe_details.find_all('div', {'class': 'mntl-recipe-details__item'})

    for item in details_items:
        label = item.find('div', {'class': 'mntl-recipe-details__label'}).text.strip()
        if label == 'Servings:':
            old_servings = int(item.find('div', {'class': 'mntl-recipe-details__value'}).text.strip())
            break
    else:
        old_servings = None

    stars = recipe_soup.find(id='mntl-recipe-review-bar__rating_2-0')
    if stars:
        stars_text = f'{stars.text} -- Ingredients:  '
    else:
        stars_text = 'Could not find stars information.'

    ingredients = []
    ingredients_html = recipe_soup.find(class_='mntl-structured-ingredients__list')
    for li in ingredients_html.find_all('li'):
        ingredient_text = li.text.strip()
        if '(' in ingredient_text and ')' in ingredient_text:
            # Remove parentheses and their contents, e.g. "(10 oz.)"
            start_index = ingredient_text.find('(')
            end_index = ingredient_text.find(')') + 1
            ingredient_text = ingredient_text[:start_index] + ingredient_text[end_index:]
        ingredient_parts = ingredient_text.split()
        try:
            amount = float(ingredient_parts[0])
            unit = ingredient_parts[1]
            name = ' '.join(ingredient_parts[2:])
            adjusted_amount = round(amount * servings / old_servings, 2)
            ingredient_text = f'{adjusted_amount} {unit} {name}'
        except (ValueError, IndexError):
            pass  # Leave ingredient text unchanged if parsing fails
        ingredients.append(ingredient_text)

    directions = []
    directions_html = recipe_soup.find(class_='comp mntl-sc-block-group--OL mntl-sc-block mntl-sc-block-startgroup')
    for li in directions_html.find_all('li'):
        directions.append(li.text.replace('.', '--').strip())

    context = {
        'recipe_url': recipe_url,
        'stars_text': stars_text,
        'servings': servings,
        'ingredients': ingredients,
        'directions': directions,
        'recipe_title': recipe_title,
        'title': title,
        'source': source,
    }
    return render(request, 'recipelist/adjusted_search.html', context)


from django.contrib.sessions.backends.db import SessionStore




def search_store(request):
    query = request.GET.get('q', '')
    url = f"https://www.google.com/search?q={query} site:allrecipes.com"
    page = requests.get(url)
    soup = BeautifulSoup(page.content, 'html.parser')
    search_results = soup.find_all('a')

    recipe_url = None
    for link in search_results:
        link_url = link.get('href')
        if link_url.startswith('/url?q=https://www.allrecipes.com/recipe/') and 'search' not in link_url:
            recipe_url = link_url.split('&')[0][7:]
            break

    if not recipe_url:
        return render(request, 'search.html', {'error_message': 'No recipe found.'})

    recipe_page = requests.get(recipe_url)
    recipe_soup = BeautifulSoup(recipe_page.content, 'html.parser')

    recipe_title = soup.find("title").text
    title, source = recipe_title.split(":")


    recipe_details = recipe_soup.find('div', {'class': 'comp recipe-details mntl-recipe-details'})
    details_items = recipe_details.find_all('div', {'class': 'mntl-recipe-details__item'})

    for item in details_items:
        label = item.find('div', {'class': 'mntl-recipe-details__label'}).text.strip()
        if label == 'Servings:':
            servings = item.find('div', {'class': 'mntl-recipe-details__value'}).text.strip()
            break
    else:
        servings = None


    stars = recipe_soup.find(id='mntl-recipe-review-bar__rating_2-0')
    if stars:
        stars_text = f'{stars.text} -- Ingredients:  '
    else:
        stars_text = 'Could not find stars information.'

    ingredients = []
    ingredients_html = recipe_soup.find(class_='mntl-structured-ingredients__list')
    for li in ingredients_html.find_all('li'):
        ingredients.append(li.text.strip())

    directions = []
    directions_html = recipe_soup.find(class_='comp mntl-sc-block-group--OL mntl-sc-block mntl-sc-block-startgroup')
    for li in directions_html.find_all('li'):
        directions.append(li.text.replace('.', '--').strip())

    context = {
        'recipe_url': recipe_url,
        'stars_text': stars_text,
        'servings': servings,
        'ingredients': ingredients,
        'directions': directions,
        'recipe_title': recipe_title,
        'title':title,
        'source':source,
    }
    return render(request, 'recipelist/search.html', context)



import os

def grocery_list(request):
    if request.method == 'POST':
        selected_ingredients = request.POST.getlist('ingredient')
        request.session['selected_ingredients'] = selected_ingredients
        context = {'selected_ingredients': selected_ingredients}

recipelist/templates/recipelist/adjusted_search.html
{% extends "recipelist/layout.html" %}

{% block content %}
    <h1>Search Results</h1>
    {% if recipe_url %}
        <p>Recipe for {{ title }}</p>
        <p>Source From: {{ source }}</p>

        <p><a href="{{ recipe_url }}" class="card-link">{{recipe_url}}</a></p>
        <form action="{% url 'recipelist:adjusted_search' %}" method="GET">
            <div class="form-group">
                <label for="servings">Servings:</label>
                <select class="form-control" name="servings" id="servings">
                    <option value="1" {% if servings == '1' %}selected{% endif %}>1</option>
                    <option value="2" {% if servings == '2' %}selected{% endif %}>2</option>
                    <option value="3" {% if servings == '3' %}selected{% endif %}>3</option>
                    <option value="4" {% if servings == '4' %}selected{% endif %}>4</option>
                    <option value="4" {% if servings == '4' %}selected{% endif %}>5</option>
                    <option value="4" {% if servings == '4' %}selected{% endif %}>6</option>
                    <option value="4" {% if servings == '4' %}selected{% endif %}>7</option>
                    <option value="4" {% if servings == '4' %}selected{% endif %}>8</option>
                    <option value="4" {% if servings == '4' %}selected{% endif %}>9</option>
                    <option value="4" {% if servings == '4' %}selected{% endif %}>10</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Adjust Servings</button>
            <input type="hidden" name="recipe_url" value="{{ recipe_url }}">
            <input type="hidden" name="title" value="{{ title }}">
            <input type="hidden" name="source" value="{{ source }}">
            <input type="hidden" name="stars_text" value="{{ stars_text }}">
            <input type="hidden" name="ingredients" value="{{ ingredients }}">
            <input type="hidden" name="directions" value="{{ directions }}">
        </form>
        <p>Servings: {{ servings }}</p>
        <p>Stars: {{ stars_text }}</p>
        <h2>Ingredients:</h2>
        <form action="{% url 'recipelist:grocery_list' %}" method="POST">
            {% csrf_token %}
            <ul>
                {% for ingredient in ingredients %}
                    <li>
                        <input type="checkbox" name="ingredient" value="{{ ingredient }}">
                        {{ ingredient }}
                    </li>
                {% endfor %}
            </ul>
            <button type="submit" class="btn btn-primary">Create Grocery List</button>
        </form>
        <h2>Directions:</h2>
        <ol>
            {% for direction in directions %}
                <li>{{ direction }}</li>
            {% endfor %}
        </ol>
    {% else %}
        <p>No results found.</p>
    {% endif %}
{% endblock %}

recipelist/templates/recipelist/grocery_list.html
{% extends 'recipelist/layout.html' %}

{% block content %}




  <h1>1. Grocery List</h1>
  <ul>
    {% for ingredient in selected_ingredients %}
      <li>{{ ingredient }}</li>
    {% endfor %}
  </ul>

  <h1>2. Login to your store</h1>
  {% if error_message %}
  <div class="alert alert-danger" role="alert">
      {{ error_message }}
  </div>
  {% endif %}
  <form method="post" action="{% url 'recipelist:login_heb' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
  </form>

{% endblock %}

recipelist/templates/recipelist/index.html
{% extends 'recipelist/layout.html' %}

{% block title %}Welcome{% endblock %}

<!DOCTYPE html>

    {% block content %}
    <title>Get Ingredients</title>
  </head>
  <body>

    <h1>Get Ingredients</h1>
    <form method="post" action="{% url 'recipelist:get_ingredients' %}">
      {% csrf_token %}
      <label for="url">Enter the URL of an Allrecipes.com recipe:</label><br>
      <input type="text" id="url" name="url"><br><br>
      <input type="submit" value="Submit">
    </form>
    {% endblock %}

recipelist/templates/recipelist/ingredients.html
% extends 'recipelist/layout.html' %}

{% block title %}Ingredients{% endblock %}

{% block content %}

{% if ingredients %}


  <h1>Ingredients:</h1>
  <p>{{ stars }}</p>
  <ul>
    {% for ingredient in ingredients %}
      <li>{{ ingredient }}</li>
    {% endfor %}
  </ul>
  <h1>Directions:</h1>
  <ol>
    {% for direction in directions %}
      <li>{{ direction }}</li>
    {% endfor %}
  </ol>
{% else %}
  <p>Could not find ingredients.</p>
{% endif %}

{% endblock %}

recipelist/templates/recipelist/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
  <div class="container">
    <img src="{% static 'images/intro.jpg' %}" alt="image is not available" width="128" height="128">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Recipe Search</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
    </div>
  </nav>
  <!-- Add this code inside the navbar -->
<form class="form-inline my-2 my-lg-0" action="{% url 'recipelist:search' %}" method="get">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
  <div class="container mt-5">


    {% block content %}{% endblock %}
  </div>
</body>
</html>

recipelist/templates/recipelist/login_heb.html
% extends 'recipelist/layout.html' %}

{% block title %}Ingredients{% endblock %}

{% block content %}


    <div class="container">
        {% if error_message %}
        <div class="alert alert-danger" role="alert">
          {{ error_message }}
        </div>
        {% endif %}

        <form method="POST" action="{% url 'recipelist:add_to_cart' %}">
          {% csrf_token %}
          <div class="mb-3">
            <label for="email" class="form-label">Username:</label>
            <input type="email" class="form-control" id="email" name="email">
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password:</label>
            <input type="password" class="form-control" id="password" name="password">
          </div>
          <button type="submit" class="btn btn-primary">Login</button>
        </form>


{% endblock %}

recipelist/templates/recipelist/order_list.html
{% extends 'recipelist/base.html' %}

{% block content %}
  <h1>Order List</h1>

  <h2>Selected Ingredients:</h2>
  <ul>
    {% for ingredient in selected_ingredients %}
      <li>{{ ingredient }}</li>
    {% endfor %}
  </ul>

  <h2>Search Results:</h2>
  <ul>
    {% for result in search_results %}
      <li>{{ result }}</li>
    {% endfor %}
  </ul>
{% endblock %}

recipelist/templates/recipelist/search.html
{% extends "recipelist/layout.html" %}

{% block content %}
    <h1>Search Results</h1>
    {% if recipe_url %}
        <p>Recipe for {{ title }}</p>
        <p>Source From: {{ source }}</p>

        <p><a href="{{ recipe_url }}" class="card-link">{{recipe_url}}</a></p>
        <form action="{% url 'recipelist:adjusted_search' %}" method="GET">
            <div class="form-group">
                <label for="servings">Servings:</label>
                <select class="form-control" name="servings" id="servings">
                    <option value="1" {% if servings == '1' %}selected{% endif %}>1</option>
                    <option value="2" {% if servings == '2' %}selected{% endif %}>2</option>
                    <option value="3" {% if servings == '3' %}selected{% endif %}>3</option>
                    <option value="4" {% if servings == '4' %}selected{% endif %}>4</option>
                    <option value="5" {% if servings == '4' %}selected{% endif %}>5</option>
                    <option value="6" {% if servings == '4' %}selected{% endif %}>6</option>
                    <option value="7" {% if servings == '4' %}selected{% endif %}>7</option>
                    <option value="8" {% if servings == '4' %}selected{% endif %}>8</option>
                    <option value="9" {% if servings == '4' %}selected{% endif %}>9</option>
                    <option value="10" {% if servings == '4' %}selected{% endif %}>10</option>

                </select>
            </div>
            <button type="submit" class="btn btn-primary">Adjust Servings</button>
            <input type="hidden" name="recipe_url" value="{{ recipe_url }}">
            <input type="hidden" name="title" value="{{ title }}">
            <input type="hidden" name="source" value="{{ source }}">
            <input type="hidden" name="stars_text" value="{{ stars_text }}">
            <input type="hidden" name="ingredients" value="{{ ingredients }}">
            <input type="hidden" name="directions" value="{{ directions }}">
        </form>
        <p>Servings: {{ servings }}</p>
        <p>Stars: {{ stars_text }}</p>
        <h2>Ingredients:</h2>

        <form action="{% url 'recipelist:grocery_list' %}" method="POST">
            {% csrf_token %}

            {% for ingredient in ingredients %}
                <li>
                    <input type="hidden" name="ingredient" value="{{ ingredient }}">
                    {{ ingredient }}
                </li>
            {% endfor %}

            <button type="submit" class="btn btn-primary">Create Grocery List</button>
        </form>


        </ul>
        <h2>Directions:</h2>
        <ol>
            {% for direction in directions %}
                <li>{{ direction }}</li>
            {% endfor %}
        </ol>
    {% else %}
        <p>No results found.</p>
    {% endif %}
{% endblock %}